name: Terraform Azure Pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_vm_admin_password: Shysha@19042025

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: >-
            {
              "clientId": "7b4464d6-33e7-4495-82f6-dd5441c87c78",
              "clientSecret": "zOz8Q~w8RR5kt4tfY4kwSkPNyGzXc0nFai2DeciG",
              "subscriptionId": "111116e2-8386-4181-b026-d821502e31cc",
              "tenantId": "1d6a29b8-43b7-4c79-9bdf-c48c5d9b44dd"
            }

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive  

      - name: Terraform Init
        working-directory: ./environment/dev
        run: terraform init -reconfigure

      - name: Terraform Validate
        working-directory: ./environment/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./environment/dev
        run: terraform plan
        
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./environment/dev
        run: terraform apply -auto-approve


